### ISSUE TITLE
[Bug] Lost of money

### ISSUE THREAD

**Issue by MrFindus** [catch441/Ultimate_Economy#77]
**Describe the bug**

**To Reproduce**
Did you changed the savefiles by yourselfe? The first times but the last times not

**[09:33:56] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Ultimate_Economy v1.2.5e
java.lang.NullPointerException: null
	at com.ue.eventhandling.EconomyVillager.handleBuySell(EconomyVillager.java:228) ~[?:?]
	at com.ue.eventhandling.EconomyVillager.handleShopInvClickEvent(EconomyVillager.java:169) ~[?:?]
	at com.ue.eventhandling.EconomyVillager.access$3(EconomyVillager.java:153) ~[?:?]
	at com.ue.eventhandling.EconomyVillager$2.performHandleInventoryClick(EconomyVillager.java:66) ~[?:?]
	at com.ue.eventhandling.UltimateEconomyEventHandler.onInvClickEvent(UltimateEconomyEventHandler.java:271) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-230]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[09:33:57] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Ultimate_Economy v1.2.5e
java.lang.NullPointerException: null
	at com.ue.eventhandling.EconomyVillager.handleBuySell(EconomyVillager.java:228) ~[?:?]
	at com.ue.eventhandling.EconomyVillager.handleShopInvClickEvent(EconomyVillager.java:169) ~[?:?]
	at com.ue.eventhandling.EconomyVillager.access$3(EconomyVillager.java:153) ~[?:?]
	at com.ue.eventhandling.EconomyVillager$2.performHandleInventoryClick(EconomyVillager.java:66) ~[?:?]
	at com.ue.eventhandling.UltimateEconomyEventHandler.onInvClickEvent(UltimateEconomyEventHandler.java:271) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-230]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[09:33:57] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Ultimate_Economy v1.2.5e
java.lang.NullPointerException: null
	at com.ue.eventhandling.EconomyVillager.handleBuySell(EconomyVillager.java:228) ~[?:?]
	at com.ue.eventhandling.EconomyVillager.handleShopInvClickEvent(EconomyVillager.java:169) ~[?:?]
	at com.ue.eventhandling.EconomyVillager.access$3(EconomyVillager.java:153) ~[?:?]
	at com.ue.eventhandling.EconomyVillager$2.performHandleInventoryClick(EconomyVillager.java:66) ~[?:?]
	at com.ue.eventhandling.UltimateEconomyEventHandler.onInvClickEvent(UltimateEconomyEventHandler.java:271) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-230]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[09:34:12] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Ultimate_Economy v1.2.5e
java.lang.NullPointerException: null
	at com.ue.eventhandling.EconomyVillager.handleBuySell(EconomyVillager.java:228) ~[?:?]
	at com.ue.eventhandling.EconomyVillager.handleShopInvClickEvent(EconomyVillager.java:169) ~[?:?]
	at com.ue.eventhandling.EconomyVillager.access$3(EconomyVillager.java:153) ~[?:?]
	at com.ue.eventhandling.EconomyVillager$2.performHandleInventoryClick(EconomyVillager.java:66) ~[?:?]
	at com.ue.eventhandling.UltimateEconomyEventHandler.onInvClickEvent(UltimateEconomyEventHandler.java:271) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-230]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]**

Maybe a crash server

**Expected behavior**
After a crash or a reboot sometime the money is reset.

**Screenshots**

**Environment**
 Paper 
 Server version : 1.14.4
 Plugin version : 1.2.5e

**Additional context**

**Comment by MrFindus** [comment]
[A list of all different error on the server.log](https://github.com/catch441/Ultimate_Economy/files/4421955/A.list.of.all.different.error.on.the.server.log)

**Comment by catch441** [comment]
Can you give me entire server log? The error above is the consequence of a error/warning on startup. Some parts of the plugin are not loaded.

**Comment by MrFindus** [comment]
[2020-04-02-2.log](https://github.com/catch441/Ultimate_Economy/files/4425798/2020-04-02-2.log)

**Comment by MrFindus** [comment]
The player shop are also unusable when we try to sell, buy, create or any command it creates an internal error.

**Comment by catch441** [comment]
What I can see is, that the playershop owner ist not loaded. Are all playershops affected? I would like to look into your playershop savefiles and you playersavefile. Can you send me these files? I will load my test server with this savefiles.

**Comment by MrFindus** [comment]
I don't understand because there isn't any problem, now the commands no longer cause an error
[P1.txt](https://github.com/catch441/Ultimate_Economy/files/4428615/P1.txt)
[P2.txt](https://github.com/catch441/Ultimate_Economy/files/4428616/P2.txt)
[PlayerFile.txt](https://github.com/catch441/Ultimate_Economy/files/4428617/PlayerFile.txt)
[P0.txt](https://github.com/catch441/Ultimate_Economy/files/4428618/P0.txt)

**Comment by catch441** [comment]
#79
