### ISSUE TITLE
[Bug] loss of money and other things

### ISSUE THREAD

**Issue by MrFindus** [catch441/Ultimate_Economy#79]
**Describe the bug**
The money has been reset and the playershops are buggy when we buy it takes no money

**To Reproduce**
Did you changed the savefiles by yourselfe? no
[latest.log](https://github.com/catch441/Ultimate_Economy/files/4480948/latest.log)
Any error in the server log?
Steps to reproduce.

**Expected behavior**

**Screenshots**
![Annotation 2020-04-15 134118](https://user-images.githubusercontent.com/57874065/79333447-d820dc00-7f1e-11ea-9988-2224102d941b.png)

**Environment**
Paper ...
 Server version 1.14.4
 Plugin version 1.2.5f

**Additional context**

**Comment by MrFindus** [comment]
for the tab-complete:

[13:45:06] [Server thread/ERROR]: Exception when Vincep13 attempted to tab complete playershop editShop 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/playershop editShop ' in plugin Ultimate_Economy v1.2.5f
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.tabCompleteCommand(CraftServer.java:1716) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.tabComplete(CraftServer.java:1688) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[patched_1.14.4.jar:git-Paper-230]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.14.4.jar:git-Paper-230]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.14.4.jar:git-Paper-230]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.PlayerConnection.lambda$a$3(PlayerConnection.java:563) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088) ~[patched_1.14.4.jar:git-Paper-230]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
	at com.ue.shopsystem.controller.PlayershopController.getPlayerShopUniqueNameList(PlayershopController.java:58) ~[?:?]
	at com.ue.shopsystem.commands.playershop.PlayershopTabCompleter.getPlayerShopList(PlayershopTabCompleter.java:137) ~[?:?]
	at com.ue.shopsystem.commands.playershop.PlayershopTabCompleter.handlePlayershopNameTabComplete(PlayershopTabCompleter.java:58) ~[?:?]
	at com.ue.shopsystem.commands.playershop.PlayershopTabCompleter.onTabComplete(PlayershopTabCompleter.java:28) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[patched_1.14.4.jar:git-Paper-230]
	... 19 more

**Comment by catch441** [comment]
cannot be reproduced with 1.2.6
