### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ghost** [catch441/Ultimate_Economy#87]
![2020-05-01_12 48 19](https://user-images.githubusercontent.com/64575231/80777942-22a28980-8baa-11ea-9810-0a3ceed93cf8.png)

Server host: Minehut (Free version)
Used plugins:
- Auto Pickup
- BetterSleeping
- bPermissions
- Essentials
- EssentialsChat
- Magic
- Matrix AntiCheat
- McMMO
- Parkour
- ProtocolLib
- Ultimate Economy

I was in the middle of setting up my townworld commands when I noticed the 'internal error' issue pop up, when I used the /plugins command I noticed that your plugin was red. What is the issue? Am I using a plugin that conflicts yours, or am I missing a dependant plugin?

**Comment by catch441** [comment]
can you send me the server log? And did you renamed a town?

**Comment by ghost** [comment]
> can you send me the server log? And did you renamed a town?

I'll try to get the log up, and I didn't rename a town. I was using the /townworld enable command to make the world town compatible in the first place.

Edit: Here's the log (I must warn you it's a big log):

> [09:15:03] [Server thread/INFO]: Starting minecraft server version 1.15.2
[09:15:03] [Server thread/INFO]: Loading properties
[09:15:03] [Server thread/INFO]: This server is running Paper version git-Paper-224 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[09:15:03] [Server thread/INFO]: Server Ping Player Sample Count: 12
[09:15:03] [Server thread/INFO]: Using 4 threads for Netty based IO
[09:15:03] [Server thread/INFO]: Debug logging is disabled
[09:15:04] [Server thread/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[09:15:04] [Server thread/INFO]: Default game type: SURVIVAL
[09:15:04] [Server thread/INFO]: Generating keypair
[09:15:04] [Server thread/INFO]: Starting Minecraft server on *:24490
[09:15:04] [Server thread/INFO]: Using epoll channel type
[09:15:06] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[09:15:15] [Server thread/WARN]: Legacy plugin bPermissions v2.12.3 does not specify an api-version.
[09:15:16] [Server thread/WARN]: Legacy plugin BetterSleeping v2.6.2 does not specify an api-version.
[09:15:16] [Server thread/INFO]: [mcMMO] Loading mcMMO v2.1.126-SNAPSHOT
[09:15:16] [Server thread/INFO]: [PlayerServer] Loading PlayerServer v1.0-SNAPSHOT
[09:15:16] [Server thread/INFO]: [Vault] Loading Vault v1.7.2-b107
[09:15:16] [Server thread/INFO]: [Ultimate_Economy] Loading Ultimate_Economy v1.2.5f
[09:15:16] [Server thread/INFO]: [bPermissions] Loading bPermissions v2.12.3
[09:15:16] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.5.0
[09:15:16] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.15.2) has not yet been tested! Proceed with caution.
[09:15:18] [Server thread/INFO]: [Matrix] Loading Matrix v4.7.6
[09:15:18] [Server thread/INFO]: [Parkour] Loading Parkour v5.3
[09:15:18] [Server thread/INFO]: [Essentials] Loading Essentials v2.17.2.0
[09:15:18] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.17.2.0
[09:15:18] [Server thread/INFO]: [Magic] Loading Magic v7.8-8ff6649
[09:15:18] [Server thread/INFO]: [BetterSleeping] Loading BetterSleeping v2.6.2
[09:15:18] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[09:15:18] [Server thread/INFO]: [Vault] Enabling Vault v1.7.2-b107
[09:15:18] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.17.2.0 which is not a depend, softdepend or loadbefore of this plugin.
[09:15:18] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[09:15:18] [Server thread/WARN]: [Vault] Loaded class de.bananaco.bpermissions.api.WorldManager from bPermissions v2.12.3 which is not a depend, softdepend or loadbefore of this plugin.
[09:15:18] [Server thread/INFO]: [Vault][Permission] bPermissions2 hooked.
[09:15:18] [Server thread/INFO]: [Vault] [Permission] bPermissions 2 found: Loaded
[09:15:18] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[09:15:18] [Server thread/INFO]: [Vault] [Vault][Chat] bPermissions2 hooked.
[09:15:18] [Server thread/INFO]: [Vault] [Chat] bPermssions2 found: Loaded
[09:15:19] [Server thread/INFO]: [Vault] Enabled Version 1.7.2-b107
[09:15:19] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.5.0
[09:15:19] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[09:15:19] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[09:15:19] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[09:15:19] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[09:15:19] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[09:15:19] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[09:15:19] [Server thread/INFO]: Preparing level "ul_Alterra"
[09:15:19] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[09:15:39] [Server thread/INFO]: Loaded 6 recipes
[09:15:39] [Server thread/INFO]: -------- World Settings For [ul_Alterra] --------
[09:15:39] [Server thread/INFO]: View Distance: 8
[09:15:39] [Server thread/INFO]: Max TNT Explosions: 100
[09:15:39] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[09:15:39] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[09:15:39] [Server thread/INFO]: Item Merge Radius: 2.5
[09:15:39] [Server thread/INFO]: Item Despawn Rate: 6000
[09:15:39] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[09:15:39] [Server thread/INFO]: Mob Spawn Range: 6
[09:15:39] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[09:15:39] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[09:15:39] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[09:15:39] [Server thread/INFO]: Experience Merge Radius: 3.0
[09:15:39] [Server thread/INFO]: Cactus Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Cane Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Melon Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Sapling Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Carrot Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Potato Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Wheat Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Vine Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Kelp Growth Modifier: 100%
[09:15:39] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[09:15:39] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[09:15:39] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911
[09:15:40] [Server thread/INFO]: -------- World Settings For [ul_Alterra_nether] --------
[09:15:40] [Server thread/INFO]: View Distance: 8
[09:15:40] [Server thread/INFO]: Max TNT Explosions: 100
[09:15:40] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[09:15:40] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[09:15:40] [Server thread/INFO]: Item Merge Radius: 2.5
[09:15:40] [Server thread/INFO]: Item Despawn Rate: 6000
[09:15:40] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[09:15:40] [Server thread/INFO]: Mob Spawn Range: 6
[09:15:40] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[09:15:40] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[09:15:40] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[09:15:40] [Server thread/INFO]: Experience Merge Radius: 3.0
[09:15:40] [Server thread/INFO]: Cactus Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Cane Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Melon Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Sapling Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Carrot Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Potato Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Wheat Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Vine Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Kelp Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[09:15:40] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[09:15:40] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911
[09:15:40] [Server thread/INFO]: -------- World Settings For [ul_Alterra_the_end] --------
[09:15:40] [Server thread/INFO]: View Distance: 8
[09:15:40] [Server thread/INFO]: Max TNT Explosions: 100
[09:15:40] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[09:15:40] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[09:15:40] [Server thread/INFO]: Item Merge Radius: 2.5
[09:15:40] [Server thread/INFO]: Item Despawn Rate: 6000
[09:15:40] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[09:15:40] [Server thread/INFO]: Mob Spawn Range: 6
[09:15:40] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[09:15:40] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[09:15:40] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[09:15:40] [Server thread/INFO]: Experience Merge Radius: 3.0
[09:15:40] [Server thread/INFO]: Cactus Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Cane Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Melon Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Sapling Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Carrot Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Potato Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Wheat Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Vine Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Kelp Growth Modifier: 100%
[09:15:40] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[09:15:40] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[09:15:40] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911
[09:15:40] [Server thread/INFO]: Preparing start region for dimension 'ul_Alterra'/minecraft:overworld
[09:15:40] [Server thread/INFO]: Loaded 0 spawn chunks for world ul_Alterra
[09:15:40] [Server thread/INFO]: Time elapsed: 359 ms
[09:15:40] [Server thread/INFO]: Preparing start region for dimension 'ul_Alterra_nether'/minecraft:the_nether
[09:15:40] [Server thread/INFO]: Loaded 0 spawn chunks for world ul_Alterra_nether
[09:15:40] [Server thread/INFO]: Time elapsed: 204 ms
[09:15:40] [Server thread/INFO]: Preparing start region for dimension 'ul_Alterra_the_end'/minecraft:the_end
[09:15:40] [Server thread/INFO]: Loaded 0 spawn chunks for world ul_Alterra_the_end
[09:15:40] [Server thread/INFO]: Time elapsed: 183 ms
[09:15:40] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.126-SNAPSHOT
[09:15:42] [Server thread/INFO]: [mcMMO] No support for repair item NETHERITE_SWORD in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for repair item NETHERITE_SHOVEL in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for repair item NETHERITE_PICKAXE in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for repair item NETHERITE_AXE in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for repair item NETHERITE_HOE in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for repair item NETHERITE_HELMET in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for repair item NETHERITE_CHESTPLATE in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for repair item NETHERITE_LEGGINGS in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for repair item NETHERITE_BOOTS in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for salvage item NETHERITE_SWORD in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for salvage item NETHERITE_SHOVEL in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for salvage item NETHERITE_PICKAXE in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for salvage item NETHERITE_AXE in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for salvage item NETHERITE_HOE in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for salvage item NETHERITE_HELMET in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for salvage item NETHERITE_CHESTPLATE in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for salvage item NETHERITE_LEGGINGS in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] No support for salvage item NETHERITE_BOOTS in this version of Minecraft, skipping.
[09:15:42] [Server thread/INFO]: [mcMMO] enabling Acrobatics Skills
[09:15:42] [Server thread/INFO]: [mcMMO] registered subskill: Roll
[09:15:43] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist
[09:15:43] [Server thread/INFO]: [PlayerServer] Enabling PlayerServer v1.0-SNAPSHOT
[09:15:43] [Server thread/INFO]: [PlayerServer] Server Id: 5ea686c5365b2318808d5f66
[09:15:43] [Server thread/INFO]: [Ultimate_Economy] Enabling Ultimate_Economy v1.2.5f
[09:15:43] [Server thread/INFO]: [Ultimate_Economy] Loading language file: 'en' 'US'
[09:15:43] [Server thread/ERROR]: Error occurred while enabling Ultimate_Economy v1.2.5f (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.Location.getChunk(Location.java:123) ~[spigot.jar:git-Paper-224]
	at com.ue.jobsystem.impl.JobcenterImpl.setupVillager(JobcenterImpl.java:127) ~[?:?]
	at com.ue.jobsystem.impl.JobcenterImpl.<init>(JobcenterImpl.java:112) ~[?:?]
	at com.ue.jobsystem.api.JobcenterController.loadAllJobCenters(JobcenterController.java:125) ~[?:?]
	at com.ue.ultimate_economy.UltimateEconomy.loadPlugin(UltimateEconomy.java:231) ~[?:?]
	at com.ue.ultimate_economy.UltimateEconomy.onEnable(UltimateEconomy.java:72) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Paper-224]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[spigot.jar:git-Paper-224]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[spigot.jar:git-Paper-224]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[spigot.jar:git-Paper-224]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[spigot.jar:git-Paper-224]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[spigot.jar:git-Paper-224]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[spigot.jar:git-Paper-224]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[spigot.jar:git-Paper-224]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[09:15:43] [Server thread/INFO]: [Ultimate_Economy] Disabling Ultimate_Economy v1.2.5f
[09:15:43] [Server thread/ERROR]: Error occurred while disabling Ultimate_Economy v1.2.5f (Is it up to date?)
java.lang.NullPointerException: null
	at com.ue.ultimate_economy.UltimateEconomy.disableVault(UltimateEconomy.java:98) ~[?:?]
	at com.ue.ultimate_economy.UltimateEconomy.onDisable(UltimateEconomy.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot.jar:git-Paper-224]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[spigot.jar:git-Paper-224]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[spigot.jar:git-Paper-224]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) ~[spigot.jar:git-Paper-224]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[spigot.jar:git-Paper-224]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[spigot.jar:git-Paper-224]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[spigot.jar:git-Paper-224]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[spigot.jar:git-Paper-224]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[spigot.jar:git-Paper-224]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[spigot.jar:git-Paper-224]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[09:15:43] [Server thread/INFO]: [bPermissions] Enabling bPermissions v2.12.3*
[09:15:43] [Server thread/WARN]: [bPermissions] == Warning: Offline mode is enabled on the server ==
[09:15:43] [Server thread/WARN]: [bPermissions] bPermissions only recommends using offline mode in scenarios where a proxy such as BungeeCord is handling mojang auth
[09:15:43] [Server thread/WARN]: [bPermissions] If there's no user authentication, users could be spoofed.
[09:15:43] [MainThread/LOAD/INFO]: [bPermissions] Permissions for world ul_alterra has loaded!
[09:15:43] [MainThread/LOAD/INFO]: [bPermissions] Permissions for world ul_alterra_nether has loaded!
[09:15:43] [MainThread/LOAD/INFO]: [bPermissions] Permissions for world ul_alterra_the_end has loaded!
[09:15:43] [Server thread/INFO]: [bPermissions] Loaded 0 custom nodes!
[09:15:43] [Server thread/INFO]: [Matrix] Enabling Matrix v4.7.6
[09:15:43] [MainThread/LOAD/INFO]: [bPermissions] Permissions for world global has loaded!
[09:15:44] [Server thread/INFO]:    _____
[09:15:44] [Server thread/INFO]:   |  |  |   Matrix AntiCheat v4.7.6
[09:15:44] [Server thread/INFO]:   |  |  |   Environment: git-Paper-224 (MC: 1.15.2)
[09:15:44] [Server thread/INFO]: 
[09:15:44] [Server thread/INFO]: [Matrix] Initializing the NMSVisitor (v1_15_R1)
[09:15:44] [Server thread/INFO]: [Matrix] Enabled 20 checks, Disabled 0 checks
[09:15:44] [Server thread/INFO]: [Matrix] Loaded all configuration files
[09:15:45] [Server thread/INFO]: [Matrix] Loaded 96 ML models
[09:15:45] [Server thread/INFO]: [Matrix] Scanning outdated log files....
[09:15:45] [Server thread/INFO]: [Matrix] Deleted 0 outdated log files!
[09:15:45] [Server thread/INFO]: [Parkour] Enabling Parkour v5.3
[09:15:45] [Server thread/INFO]: [Parkour] [Vault] Successfully linked. Version: 1.7.2-b107
[09:15:46] [Server thread/INFO]: [Parkour] Enabled Parkour v5.3
[09:15:46] [Server thread/INFO]: [Essentials] Enabling Essentials v2.17.2.0
[09:15:46] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[09:15:46] [Server thread/INFO]: [Essentials] No kits found to migrate.
[09:15:46] [Server thread/INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[09:15:46] [Server thread/INFO]: [Essentials] Using 1.13+ flat spawn egg provider as spawn egg provider.
[09:15:46] [Server thread/INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[09:15:46] [Server thread/INFO]: [Essentials] Loaded 21018 items from items.json.
[09:15:46] [Server thread/INFO]: [Essentials] Using locale en_US
[09:15:46] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[09:15:46] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[09:15:46] [Server thread/INFO]: [Vault] [Vault][Economy] Essentials Economy hooked.
[09:15:46] [Server thread/INFO]: [Essentials] Using Vault based permissions (bPermissions)
[09:15:46] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.17.2.0
[09:15:46] [Server thread/INFO]: [Magic] Enabling Magic v7.8-8ff6649
[09:15:47] [Server thread/INFO]: [Magic] EffectLib initialized
[09:15:48] [Server thread/INFO]: [Magic] Wand crafting is enabled
[09:15:48] [Server thread/INFO]: [Magic] Skin-based spell icons disabled
[09:15:48] [Server thread/INFO]: [Magic] Vault found, 'currency' cost types available
[09:15:48] [Server thread/INFO]: [Magic] Loaded 0 attributes
[09:15:48] [Server thread/INFO]: [Magic] Registered attributes: [bowpull]
[09:15:48] [Server thread/INFO]: [Magic] Registered currencies: item,mana,xp,health,currency,sp,levels,hunger
[09:15:48] [Server thread/INFO]: [Magic] Loaded 6 effect lists
[09:15:48] [Server thread/INFO]: [Magic] Loaded 396 items
[09:15:50] [Server thread/INFO]: [Magic] Loaded 519 spells
[09:15:50] [Server thread/INFO]: [Magic] Loaded 6 classes
[09:15:50] [Server thread/INFO]: [Magic] Loaded 4 automata templates
[09:15:50] [Server thread/INFO]: [Magic] Loaded 15 progression paths
[09:15:50] [Server thread/INFO]: [Magic] Loaded 144 wands
[09:15:50] [Server thread/INFO]: [Magic] Loaded 21 mob templates
[09:15:50] [Server thread/INFO]: [Magic] Loaded 20 crafting recipes
[09:15:50] [Server thread/INFO]: [Magic] LibsDisguises not found, magic mob disguises will not be available
[09:15:50] [Server thread/INFO]: [Magic] MobArena not found
[09:15:50] [Server thread/INFO]: [Magic] LogBlock not found
[09:15:50] [Server thread/INFO]: [Magic] Integrating with Essentials for Recall warps
[09:15:50] [Server thread/INFO]: [Magic] Factions not found
[09:15:50] [Server thread/INFO]: [Magic] WorldGuard not found, region protection and pvp checks will not be used.
[09:15:50] [Server thread/INFO]: [Magic] Towny not found, region protection and pvp checks will not be used.
[09:15:50] [Server thread/INFO]: [Magic] Lockette nor LockettePro found, will not integrate.
[09:15:50] [Server thread/INFO]: [Magic] GriefPrevention not found, claim protection will not be used.
[09:15:50] [Server thread/INFO]: [Magic] NoCheatPlus not found, will not integrate.
[09:15:50] [Server thread/INFO]: [Magic] dynmap not found, not integrating.
[09:15:50] [Server thread/INFO]: [Magic] Citizens not found, Magic trait unavailable.
[09:15:50] [Server thread/INFO]: [Magic] LightAPI not found, Light action will not work
[09:15:50] [Server thread/INFO]: [Magic] Activated BStats
[09:15:50] [Server thread/INFO]: Resource pack configured in server.properties, Magic not using RP from config.yml
[09:15:50] [Server thread/INFO]: [BetterSleeping] Enabling BetterSleeping v2.6.2*
[09:15:50] [Server thread/INFO]: [BetterSleeping] No missing options were found in config.yml!
[09:15:50] [Server thread/INFO]: [BetterSleeping] No missing options were found in lang.yml!
[09:15:50] [Server thread/INFO]: [BetterSleeping] No enabled sleeping buffs were found!
[09:15:50] [Server thread/INFO]: [BetterSleeping] Successfully hooked into Essentials!
[09:15:50] [Thread-12/INFO]: [BetterSleeping] You are using the latest version: 2.6.2
[09:15:51] [Server thread/INFO]: Done (32.605s)! For help, type "help"
[09:15:51] [Server thread/INFO]: Timings Reset
[09:15:52] [Craft Scheduler Thread - 6/INFO]: [Matrix] Start checking update....
[09:15:52] [Craft Scheduler Thread - 11/INFO]: [Vault] Checking for Updates ... 
[09:15:52] [Craft Scheduler Thread - 6/INFO]: > Matrix Updater:
[09:15:52] [Craft Scheduler Thread - 6/INFO]:     Matrix has an update: 4.7.9 current version: 4.7.6
[09:15:52] [Craft Scheduler Thread - 6/INFO]:     Download link: https://www.mc-market.org/resources/13999/
[09:15:52] [Craft Scheduler Thread - 11/INFO]: [Vault] No new version available
[09:15:52] [Craft Scheduler Thread - 7/INFO]: [Matrix] Plugin Enabled
[09:15:53] [Server thread/INFO]: [Magic] Essentials found, hooked up custom item handler
[09:15:53] [Server thread/INFO]: [Magic] Loading image map data from imagemaps.yml
[09:15:53] [Server thread/INFO]: [Magic] Loaded 0 image maps
[09:15:53] [Server thread/INFO]: [Magic] Finished loading data.
[09:16:08] [User Authenticator #1/INFO]: UUID of player _TotallyNotASpy_ is 52deb187-d952-4843-b616-4cbaefd124a8
[09:16:09] [Server thread/INFO]: _TotallyNotASpy_ joined the game
[09:16:09] [Server thread/INFO]: _TotallyNotASpy_[/130.169.233.199:51630] logged in with entity id 95 at ([ul_Alterra_nether]-112.01398658700582, 61.0, -24.417247065065272)
[09:16:16] [Server thread/INFO]: [mcMMO] WorldGuard was not detected.
[09:16:30] [Server thread/INFO]: _TotallyNotASpy_ issued server command: /gamemode creative
[09:16:45] [Server thread/INFO]: _TotallyNotASpy_ has made the advancement [Ice Bucket Challenge]
[09:17:18] [Server thread/INFO]: _TotallyNotASpy_ issued server command: /plugins
[09:17:32] [Server thread/INFO]: _TotallyNotASpy_ issued server command: /dl log

**Comment by catch441** [comment]
did you delete a world?

**Comment by ghost** [comment]
> did you delete a world?

I don't believe so, I uploaded a world that already had admin shops and switched to that for my server, and all the shops were still there, but I couldn't use any commands to change anything.
I however cannot confirm whether or not the plugin was working before or after the world change since I was using the old world for about 4 real life hours without using any commands or checking the plugin's status before swapping worlds.

**Comment by catch441** [comment]
one of the jobcenters has a invalid world as location. Opeb the savefile plugins/Ultimate_Economy/ <name>_jobcenter.yml and change the world name to a name of a world you have

**Comment by ghost** [comment]
Since this is my first time dealing with the file manager, I don't know how to access the .yml file from the website.

**Comment by ghost** [comment]
Alright, I managed to figure this out on my own. I deleted all the worlds except the one I use in the server as well as all the yml files for the jobs and the shops from the file manager, and now the plugin works again.

Before I close this issue, I really want to thank you for sticking around. I love this plugin a lot and I'm glad you took the time to help me.

Stay awesome catch441.
